# -*- coding: utf-8 -*-
"""Welkom bij Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

# --- PHASE 1: DATA COLLECTION ---
# Deze URL is 'statisch', wat betekent dat BeautifulSoup de tabel direct kan zien.
url = "https://www.timeanddate.com/weather/belgium/brussels/ext"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
}

print(f"Stap 1: Weer data ophalen van {url}...")

try:
    response = requests.get(url, headers=headers, timeout=20)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")

        # De tabel op deze site heeft een heel duidelijk ID: 'wt-ext'
        table = soup.find("table", id="wt-ext")

        weather_data = []
        if table:
            tbody = table.find("tbody")
            rows = tbody.find_all("tr")

            for row in rows[:10]: # Pak de komende 10 dagen
                cols = row.find_all(["th", "td"])
                if len(cols) > 2:
                    # Kolom 0 is de datum, Kolom 2 is de temperatuur (bijv. "12 / 8 °C")
                    dag = cols[0].get_text(strip=True)
                    temp_ruw = cols[2].get_text(strip=True)

                    weather_data.append({
                        "Dag": dag,
                        "Temp_Ruw": temp_ruw
                    })

        df = pd.DataFrame(weather_data)

        if not df.empty:
            print("\n--- Phase 1 Geslaagd: Ruwe data verzameld ---")
            print(df.head())

            # --- PHASE 2: DATA CLEANING ---
            print("\nStap 2: Data opschonen (Cleaning)...")

            # Uitleg Cleaning:
            # De data is nu: "14 / 9 °C"
            # 1. We splitsen op de '/' en pakken het eerste deel (de max temp)
            # 2. We halen "°C" weg
            # 3. We maken er een echt getal (float) van

            df['Temp_Celsius'] = df['Temp_Ruw'].apply(lambda x: x.split('/')[0].replace('°C', '').strip())
            df['Temp_Celsius'] = pd.to_numeric(df['Temp_Celsius'])

            print("--- Phase 2 Geslaagd: Data is nu bruikbaar voor analyse ---")
            print(df[['Dag', 'Temp_Celsius']].head())

            # Opslaan voor je verslag
            df.to_csv("weer_brussel_clean.csv", index=False)
            print("\nBestand 'weer_brussel_clean.csv' is opgeslagen!")
        else:
            print("Kon de tabel 'wt-ext' niet vinden. Is de site layout gewijzigd?")
    else:
        print(f"Fout: Statuscode {response.status_code}")

except Exception as e:
    print(f"Er ging iets mis: {e}")

# Check what your DataFrame looks like right now
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nFirst 3 rows:")
df.head(3)

# Final check
print(f"Rows: {len(df)}")
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nSample:")
df.head()

df.to_csv("verify_output.csv", index=False)
print(f"Rows: {len(df)}  |  Columns: {list(df.columns)}")
df

import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime
import os
from supabase import create_client

# --- STAP 1: CONFIGURATIE & TIJDSTEMPEL ---
# Gebruik os.environ voor veiligheid op GitHub
SUPABASE_URL = "https://cdpvocdzgerxadnntnia.supabase.co"
SUPABASE_KEY = "sb_publishable_HURhmxus4iEml1F5F5DPbw_jQAxNn15" # De volledige sleutel

# Leg het moment van de scrape vast voor je tijdreeks-analyse (Phase 4)
scrape_time = datetime.now().isoformat()

# --- STAP 2: SCRAPER (PHASE 1) ---
url = "https://www.timeanddate.com/weather/belgium/brussels/ext"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}

print(f"Systeem start: Scraper uitgevoerd op {scrape_time}")

try:
    response = requests.get(url, headers=headers, timeout=20)
    response.encoding = "utf-8"
    soup = BeautifulSoup(response.text, "html.parser")

    table = soup.find("table", id="wt-ext")
    rows_list = []

    if table:
        tbody = table.find("tbody")
        for row in tbody.find_all("tr")[:10]: # Pak de komende 10 dagen
            cols = row.find_all(["th", "td"])
            if len(cols) > 2:
                dag = cols[0].get_text(strip=True)
                temp_ruw = cols[2].get_text(strip=True)

                # --- STAP 3: DATA CLEANING (PHASE 2) ---
                # We maken hier direct het schone getal aan
                try:
                    temp_schoon = float(temp_ruw.split('/')[0].replace('°C', '').strip())
                except:
                    temp_schoon = 0.0

                rows_list.append({
                    "forecast_day": dag,
                    "temp_raw": temp_ruw,
                    "temp_celsius": temp_schoon,
                    "scraped_at": scrape_time  # De tijdstempel uit stap 1
                })

        # Maak DataFrame voor analyse en alerts
        df = pd.DataFrame(rows_list)

        if not df.empty:
            # --- STAP 4: DATABASE INSERT (SUPABASE) ---
            supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
            result = supabase.table("brussels_weather").insert(rows_list).execute()
            print(f"✅ Succes: {len(rows_list)} rijen toegevoegd aan Supabase.")

            # --- STAP 5: BUSINESS ALERTS ---
            # Alert 1: Hitte-check
            max_temp = df['temp_celsius'].max()
            if max_temp > 25:
                print(f"⚠️ ALERT: Warme dag gedetecteerd ({max_temp}°C). Marketing aanpassen!")

            # Alert 2: Vorst-check
            min_temp = df['temp_celsius'].min()
            if min_temp < 0:
                print(f"⚠️ ALERT: Vorst voorspeld ({min_temp}°C). Check logistiek/zout!")

        else:
            print("Fout: Geen rijen gevonden in de tabel.")
    else:
        print("Fout: Tabel 'wt-ext' niet gevonden op de pagina.")

except Exception as e:
    print(f"❌ Kritieke fout in pipeline: {e}")